[server]
headless = true
port = 80

[theme]
base = "light"
primaryColor = "199, 222, 227"
backgroundColor = "199, 222, 227"
secondaryBackgroundColor = "#c7dee3"
textColor = "#262730"
font = "sans serif"